print("SJC22MCA-20227-Georgekutty Biju\nS3MCA")
import pandas as pd
iris_data=pd.read_csv('iris.csv')
print("shape of the dataset: ",iris_data.shape)
print("First 5 rows of the Dataset: ")
print(iris_data.head())
print("\nLast 5 rows of the dataset: ")
print(iris_data.tail())
print("Size of the dataset: ",iris_data.size)
print("\nNumber of samples available for each variety: ")
sample_count=iris_data['variety'].value_counts()
print(sample_count)
print("Description of the dataset: ")
description=iris_data.describe()
print(description)
